name: CI
on: 
  push: 
  pull_request:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Branch name
        run: echo running on branch pull/${{ github.event.pull_request.number }}/head:${{ github.head_ref }} && echo running on branch ${{ github.head_ref }}
      - name: test run 
        run: |
          cd /home/ckb/axon-devops/docker-deploy
          make deploy
          


